apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: rust-env-ingress
  namespace: default
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
        - path: /
          pathType: Exact
          backend:
            service:
              name: rust-env
              port:
                number: 3000
